[package]
name = "rpl-stdlib"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "rpl"
path = "bin/rpl.rs"

[dependencies]
rpl = { workspace = true }
rpl-vm = { workspace = true }
