[package]
name = "rpl-lsp"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rpl-lsp"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
rpl-session = { path = "../rpl-session" }
lsp-types = "0.97"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
