[package]
name = "rpl-project"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
rpl = { workspace = true }
rpl-stdlib = { workspace = true }
toml = "0.8"
glob = "0.3"
walkdir = "2"
thiserror = { workspace = true }
serde = { workspace = true }
