[package]
name = "rpl-session"
version = "0.1.0"
edition = "2024"

[dependencies]
rpl-core = { path = "../rpl-core" }
rpl-source = { path = "../rpl-source" }
rpl-lang = { path = "../rpl-lang" }
rpl-stdlib = { path = "../rpl-stdlib" }
